# Day01 Python Libraries
## Hussein Mohamed
---

In [1]:
import numpy as np

### Q1
#### Write a NumPy program to create an array of 10 zeros, array of 10 ones, and array of 10 fives.

In [2]:
q1zeros = np.zeros(10, dtype=int)
q1ones = np.ones(10, dtype=int)
q1fives = np.ones(10, dtype=int) * 5
q1fives2 = np.array([5] * 10)
print(f"{q1zeros}\n{q1ones}\nmethod1: {q1fives}\nmethod2: {q1fives2}")

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
method1: [5 5 5 5 5 5 5 5 5 5]
method2: [5 5 5 5 5 5 5 5 5 5]


---

### Q2
#### Write a NumPy program to create an array of all even integers from 30 to 70.
---

In [3]:
q2even_integers = np.arange(30, 71, 2)
print(q2even_integers)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


---

### Q3
#### Write a NumPy program to create an array of given shape (5,6) and integer type, filled with zeros. 

---

In [4]:
q3zeros_shape1 = np.zeros(30, dtype = int ).reshape(5,6)
q3zeros_shape2 = np.zeros((5,6), dtype = int )
print(f"method one:\n{q3zeros_shape1}\nmethod2:\n{q3zeros_shape2}")

method one:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
method2:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


---

### Q4
#### Create a 10x10 array with random values and find the minimum and maximum values.

---

In [5]:
q4rand = np.random.rand(10,10)
print(q4rand)
print(f"min: {q4rand.min()}\nmax: {q4rand.max()}")

[[0.68848115 0.33964999 0.3076726  0.53532394 0.67951008 0.28511844
  0.3026504  0.80484521 0.41652772 0.50084433]
 [0.37918546 0.4762864  0.17001161 0.74660563 0.72928163 0.42579115
  0.56630488 0.52829639 0.85924483 0.78553112]
 [0.64989072 0.74950767 0.69337414 0.28317071 0.76404802 0.41373362
  0.33381705 0.1737418  0.83071002 0.08935201]
 [0.6111145  0.19532568 0.96819575 0.66672867 0.50548305 0.65112175
  0.17559607 0.89446129 0.7679587  0.99246896]
 [0.5602928  0.86122503 0.8774952  0.61029383 0.15462301 0.62360178
  0.07800418 0.82652277 0.72280287 0.84717858]
 [0.12141321 0.73145066 0.19986345 0.60568475 0.5184521  0.79271868
  0.60912798 0.83123033 0.46209435 0.03459088]
 [0.04683999 0.30738705 0.14063305 0.61598958 0.58709886 0.35886363
  0.19816252 0.83844077 0.99515364 0.38030699]
 [0.4570673  0.57286566 0.08084972 0.15789277 0.52255752 0.27564774
  0.63152623 0.07431422 0.50076218 0.89583168]
 [0.72131546 0.25419847 0.75812108 0.59945921 0.32866853 0.7606938
  0.20132357 

---

### Q5
#### Write a NumPy program to create a 3x3 array with values ranging from 2 to 10.

---

In [6]:
q5array = np.arange(2, 11).reshape(3,3)
print(q5array)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


---

### Q6
#### Write a NumPy program to create an array of size = 20 using arrange, then extract all numbers from a given array greater than 15.

---

In [7]:
q6array = np.arange(20)
for i in q6array:
    if i > 15:
        print(i)

16
17
18
19


---

### Q7
#### Write a NumPy program to combine the two 2-dimensional arrays using hstack and vstack.
- Array 1: [[0, 1, 3], [5, 7, 9]]
- Array 2: [[0, 2, 4], [6, 8, 10]]

---

In [8]:
q7arr1 = np.array([[0, 1, 3], [5, 7, 9]])
q7arr2 = np.array([[0, 2, 4], [6, 8, 10]])
q7hstack = np.hstack((q7arr1, q7arr2))
q7vstack = np.vstack((q7arr1, q7arr2))
q7concat0 = np.concatenate((q7arr1, q7arr2), axis=0)
q7concat1 = np.concatenate((q7arr1, q7arr2), axis=1)
print(f"hstack:\n{q7hstack}\nvstack:\n{q7vstack}\nconcat axis0:\n{q7concat0}\nconcat axis1:\n{q7concat1}")

hstack:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
vstack:
[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]
concat axis0:
[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]
concat axis1:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


---

### Q8
#### Write a NumPy program to create ones array of size 10 and change the 6th element to 11.

---

In [9]:
q8ones = np.ones(10, dtype=int)
q8ones[5] = 11
print(q8ones)

[ 1  1  1  1  1 11  1  1  1  1]


---

### Q9
#### Write a NumPy program to append a value to the end of an array.

---

In [10]:
print(np.append(q8ones, 99))

[ 1  1  1  1  1 11  1  1  1  1 99]


---

### Q10
#### Write a NumPy program to reverse an array [using two different methods].

---

In [11]:
q10reverse = np.array([1, 2, 3, 4, 5])
print(f"method1: {q10reverse[::-1]}\nmethod2: {np.flip(q10reverse)}")


method1: [5 4 3 2 1]
method2: [5 4 3 2 1]
